-- Force permissions fix for collections table

-- 1. Ensure table exists and RLS is enabled
CREATE TABLE IF NOT EXISTS collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  active BOOLEAN DEFAULT TRUE
);
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;

-- 2. NUCLEAR OPTION: Drop ALL policies on this table
DROP POLICY IF EXISTS "Enable read access for all users" ON collections;
DROP POLICY IF EXISTS "Enable full access for authenticated users" ON collections;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON collections;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON collections;
DROP POLICY IF EXISTS "Enable delete for authenticated users only" ON collections;
DROP POLICY IF EXISTS "Public can view active collections" ON collections;
DROP POLICY IF EXISTS "Admins can manage collections" ON collections;
DROP POLICY IF EXISTS "Enable everything for authenticated" ON collections;
DROP POLICY IF EXISTS "Allow public read" ON collections;

-- 3. Simple, explicit policies

-- Policy 1: Public Read (Select Only)
CREATE POLICY "Public Read Access"
ON collections FOR SELECT
USING (true);

-- Policy 2: Authenticated Users Full Access (Insert, Update, Delete)
-- Using 'authenticated' role + true check to be as permissive as possible for logged users
CREATE POLICY "Authenticated Admin Access"
ON collections FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 4. Grant Permissions (Crucial for 401/403 errors)
GRANT ALL ON collections TO authenticated;
GRANT ALL ON collections TO service_role; -- Ensure service role has access
GRANT SELECT ON collections TO anon;

-- 5. Sequence Permissions (Crucial for Insert errors)
GRANT USAGE, SELECT ON SEQUENCE collections_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE collections_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE collections_id_seq TO anon; -- Sometimes needed if ID returned on select
