-- 1. Create collections table
CREATE TABLE IF NOT EXISTS collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  slug TEXT NOT NULL, -- Removing UNIQUE constraint on creation to avoid issues if data exists, but ideally should be unique
  active BOOLEAN DEFAULT TRUE
);

-- 2. Add collection_ids to products
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'collection_ids') THEN
        ALTER TABLE products ADD COLUMN collection_ids BIGINT[] DEFAULT '{}';
    END IF;
END $$;

-- 3. Enable RLS
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;

-- 4. Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Enable read access for all users" ON collections;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON collections;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON collections;
DROP POLICY IF EXISTS "Enable delete for authenticated users only" ON collections;
DROP POLICY IF EXISTS "Public can view active collections" ON collections;
DROP POLICY IF EXISTS "Admins can manage collections" ON collections;

-- 5. Create Policies

-- Allow public read access (so Catalog works)
CREATE POLICY "Enable read access for all users"
ON collections FOR SELECT
USING (true);

-- Allow authenticated users to insert, update, delete (Admin)
CREATE POLICY "Enable full access for authenticated users"
ON collections FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 6. Grant permissions
GRANT ALL ON collections TO authenticated;
GRANT SELECT ON collections TO anon;
GRANT USAGE, SELECT ON SEQUENCE collections_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE collections_id_seq TO anon;
