export { Home } from './Home'
export { Catalog } from './Catalog'
export { HowItWorks } from './HowItWorks'
export { About } from './About'
export { Checkout } from './Checkout'
export { PrivacyPolicy } from './PrivacyPolicy'
export { TermsOfService } from './TermsOfService'
